#+title: Minaduki

* Introduction

Minaduki is my fork of Org-roam v1.

It has support for reading Obsidian vaults.

* Concepts
** Vaults

A vault has a name and a path. This tells Minaduki which folders to index and how to link to each folder.

Links can specify a vault. If a link doesn't specify a vault, that makes it a normal relative or absolute link, so it will refer to paths inside the current vault.

Additionally, some commands like =minaduki/open-index= will use a default vault.

- Variable: minaduki/vaults

  A list of vaults. Each vault is represented with a list =(NAME PATH)=; more properties might be added in the future.

  #+begin_src elisp
  (setq minaduki/vaults
        '(("notes" "~/notes")
          ("cloud" "~/Dropbox")))
  #+end_src

The name of a vault can be used to link to it. In Org this is the same as setting =org-link-abbrev-alist=. In this example, to link to =~/Dropbox=, write:

#+begin_src org
[[cloud:myfile.org]]
#+end_src

which will refer to =~/Dropbox/myfile.org=.

Right now the main vault is set with =org-directory=.

Subdirectories containing ~minaduki-nested-vault-root-files~ are considered /nested vaults/. Right now this is only used to implement Obsidian's default /shortest link when possible/ links.

- [ ] Markdown: following adheres to minaduki/vaults
- [ ] Markdown: extracting adheres to minaduki/vaults
- [ ] Markdown: insertion adheres to minaduki/vaults
** Keywords

- title :: the main title of the file. (TODO: multiple title keywords should be concatenated)
- created :: the timestamp (in =YYYY-MM-DDThh:mm:ssZ=) when the file was first created
- alias :: an alternative title.
- (to be renamed) =roam_key= :: a unique identifier for this file. Could be a link or any other ID. This is used to associate bibliography items with note files, as well as for citation backlinks.
- (to be renamed) =roam_tags= :: a list of tags.

** Bibliography

Bibliography entries are written in a custom Org-based format. Support for other formats like BibTeX is planned.

Set bibliography files with =minaduki-lit/bibliography=.

Use =minaduki/literature-entries= to browse all literature entries. After you select an entry, you can:

- insert a citation to the entry
- copy its key
- edit its associated note (the one that has a =roam_key= equal to this entry)
- insert a link to its associated note
- show the definition of the entry in the bibliography, or
- open its associated URL, DOI, or PDF.

This is essentially my reimplementation of =bibtex-completion=.

Org-cite is supported: instead of using =org-cite-global-bibliography= you can just use =minaduki-lit/bibliography= and =org-cite-insert= will offer completions from the right place. This is accomplished with a custom Org-cite processor.

Reading from Org-cite's local bibliography is not yet supported though.

* Tutorials
** Browsing notes

Use =minaduki/open= to see a list of indexed notes. Select one to open.

If [[https://github.com/minad/marginalia/][Marginalia]] is installed, you'll see the file name listed in the completion as well.

Press RET to visit the note.

Headline notes are indicated with a leading star (regardless of heading level or whether it's Markdown or Org). Headline notes are headlines that have an =ID= property.

** Obsidian support

Obsidian links are supported. You can follow them, and they are tracked by backlinks.

In an Obsidian vault, the file name is used as the main title.

Try cloning a public Obsidian vault like [[https://github.com/sw-yx/brain][sw-yx/brain]] or [[https://help.obsidian.md/][Obsidian Help]]. Backlinks and title search should just work.
